=== TurneaDavid-Catalin/web-app-vanilla-js-demo/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT persoana (nume, prenume, varsta, adresa, educatie)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT educatie (nivel, domeniu, institutie, an, ocupatie)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT domeniu (#PCDATA)>
<!ELEMENT institutie (#PCDATA)>
<!ELEMENT an (#PCDATA)>
<!ELEMENT ocupatie (#PCDATA)>

=== TurneaDavid-Catalin/web-app-vanilla-js-demo/persoane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>Strada Libertății</strada>
            <numar>10</numar>
            <localitate>Felesti</localitate>
            <judet>Neamt</judet>
            <tara>România</tara>
        </adresa>
        <educatie>
            <nivel>Facultate</nivel>
            <domeniu>Automatica</domeniu>
            <institutie>Universitatea Tehnica Iasi</institutie>
            <an>2020</an>
            <ocupatie>Inginer</ocupatie>
        </educatie>
    </persoana>
        <persoana id="2">
        <nume>Tanase</nume>
        <prenume>Cristi</prenume>
        <varsta>34</varsta>
        <adresa>
            <strada>Strada Lalelelor</strada>
            <numar>23</numar>
            <localitate>Bucuresti</localitate>
            <judet>Bucuresti</judet>
            <tara>România</tara>
        </adresa>
        <educatie>
            <nivel>Liceu</nivel>
            <domeniu>Sportiv</domeniu>
            <institutie>FCSB</institutie>
            <an>2012</an>
            <ocupatie>Jucator</ocupatie>
        </educatie>
    </persoana>
        <persoana id="3">
        <nume>Ionescu</nume>
        <prenume>Mihai</prenume>
        <varsta>57</varsta>
        <adresa>
            <strada>Strada Sclaviei</strada>
            <numar>66</numar>
            <localitate>Damuc</localitate>
            <judet>Neamt</judet>
            <tara>România</tara>
        </adresa>
        <educatie>
            <nivel>Facultate</nivel>
            <domeniu>Economie</domeniu>
            <institutie>FEEA</institutie>
            <an>1990</an>
            <ocupatie>Contabil</ocupatie>
        </educatie>
    </persoana>
</persoane>
